# Generated by Django 5.2.5 on 2025-08-16 12:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("leads", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="lead",
            name="company_name",
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name="lead",
            name="designation",
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
