# Generated by Django 5.2.5 on 2025-08-16 14:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("leads", "0002_lead_company_name_lead_designation"),
    ]

    operations = [
        migrations.AddField(
            model_name="lead",
            name="country_code",
            field=models.CharField(blank=True, max_length=8),
        ),
    ]
